version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5500:3000
    env_file:
      - .env
    restart: on-failure
  mysql:
    image: mysql:8
    ports:
      - "19998:3306"
    volumes:
      - ./volumes/db:/var/lib/mysql
    depends_on:
      - mysql
    environment:
      MYSQL_DATABASE: sornrubsom
      MYSQL_ROOT_PASSWORD: "CPE241!sornrubsom"
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8002:80"
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 512M
    depends_on:
      - mysql
