version: "3.8"
services:
  app:
    container_name: go-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5500:3000
    env_file:
      - .env
    restart: on-failure
    networks:
      - my_network
  mysql:
    image: mysql:8
    ports:
      - "19998:3306"
    environment:
      MYSQL_DATABASE: sornrubsom
      MYSQL_ROOT_PASSWORD: "CPE241!sornrubsom"
    networks:
      - my_network
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8002:80"
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 512M
    depends_on:
      - mysql
    networks:
      - my_network

networks:
  my_network:
