version: "3.8"
services:
  app:
    container_name: go-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5500:3000
    restart: on-failure
    depends_on:
      - mysql
    environment:
      DB_URL: root:CPE241!sornrubsom@tcp(mysql:3306)/sornrubsom

  mysql:
    image: mysql:latest
    ports:
      - "19998:3306"
    volumes:
      - ~/cpe241DB/volumes/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: sornrubsom
      MYSQL_ROOT_PASSWORD: "CPE241!sornrubsom"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8002:80"
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 512M
    depends_on:
      - mysql
